modLoader = "javafml"

loaderVersion = "[36,)"

license = "LGPL-2.1 License"

issueTrackerURL = "https://github.com/psyGamer/Construct/issues/"

[[mods]]
modId = "construct"
version = "${file.jarVersion}"
displayName = "Construct"

description = '''
A library for simplifying common tasks in Minecraft Forge
'''

#updateJSONURL = "https://www.curseforge.com/minecraft/mc-mods/construct-library"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/construct-library"

#logoFile = "logo.png"

#credits = "Thanks for this example mod goes to Java"
authors = "psyGamer"

[[dependencies.construct]]
modId = "forge"
versionRange = "[36,)"
mandatory = true

ordering = "NONE"
side = "BOTH"

[[dependencies.construct]]
modId = "minecraft"
versionRange = "[1.16.5,1.17)"
mandatory = true

ordering = "NONE"
side = "BOTH"
